### ISSUE TITLE
[FEAT] 메모앱 클론코딩

### ISSUE THREAD

**Issue by sy5072** [feldblume5263/JJANGCRO_Study#2]
## 💡 Issue

메모앱 클론코딩입니다.

## 📝  todo
- [ ] 리스트 뷰 레이아웃 구현
- [ ] 갤러리뷰 레이아웃 구현
- [ ] 메모 작성 레이아웃 구현
- [ ] 데이터 관리 연결
- [ ] 정렬 순서 변경
